### ISSUE TITLE
xbacklight never works for me in xmonad.hs

### ISSUE THREAD

**Issue by dlgeraghty** [arcolinux/arcolinux-xmonad-xmobar#1]
Hi, I usually do installs of arcolinux every month in different laptops.
my brightness keys never work out of the box, I always have to do some research on how to get them working. After doing so manually a bunch of times, I have observed that for me, brightnessctl always work. 
So I am proposing this change:

> Instead of:
```
  -- Increase brightness
  , ((0, xF86XK_MonBrightnessUp),  spawn $ "xbacklight -inc 5")

  -- Decrease brightness
  , ((0, xF86XK_MonBrightnessDown), spawn $ "xbacklight -dec 5")

```
> For me it works:
```  
-- Increase brightness
  , ((0, xF86XK_MonBrightnessUp),  spawn $ "brightnessctl s 5%+")

  -- Decrease brightness
  , ((0, xF86XK_MonBrightnessDown), spawn $ "brightnessctl s 5%-")

```

**Comment by arcolinuxz** [comment]
Will add it to the code as alternative
